export default [
    "I love that you love animation films and watch them so often, I find it so cute",
    "I love how you get so flustered when I learn something new about you sometimes, I like getting to know you better and better",
    "I love getting to have intellectual conversations with you, I like that we can pick our brains together and learn from each other",
    "I love that you like to dress nicely and look good, I think you look so cute when you do",
    "Your Instagram aesthetic is like the most beautiful thing I’ve ever seen, I love looking at your photos and seeing the world through your eyes",
    "I love that we have Ferkie and Charles in our imaginary world",
    "I love how considerate you are and have showed that to me in so many ways",
    "Your giggle is the most adorable thing I’ve ever heard, it makes me so happy to hear you laugh",
    "Building our future together in NYC or Europe is something I look forward to every day, I'm so grateful to have found someone who shares my dreams",
    "I love your body and all its curves, I think they're so sexy and I don't know when 'fat' is even a word that comes to mind when you look at it",
    "You are my eepy little princess, and I love you so much",
    "i love the softness of your cheeks and the way you look at me",
    "You make me a better person, and everyday I try to be better for you",
    "I love that we have started to learn some Italian together",
    "Your smile is my favorite thing to see every day.",
    "I like that you hold me accountable at times, it shows how much you care about me",
    "I love that you've gotten me into R&B and Mariah Carey, and so much other new music",
    "I love all the silly reels you send me about our relationship, and how you pretend you're the boss of the relationship",
    "I love seeing your smile when I am able to Deliveroo something to you",
    "I love you're ability to be so focused and driven",
    "I love that you like to try different foods and restaurants, it makes our dates so fun and exciting",
    "You're my favorite place to come home to.",
    "You look like you were painted by someone who loves you deeply.",
    "Even time seems to pause to admire you.",
    "You’re the poem my heart didn’t know how to write.",
    "I see galaxies in your eyes when you look at me.",
    "You make existing feel magical.",
    "You make me believe that some people are made of stars.",
    "If I could bottle the feeling of holding you, I’d live in it forever.",
    "Every moment with you feels like a secret between my soul and the universe.",
    "You have the kind of beauty that makes flowers jealous.",
    "You make love feel like a quiet, steady miracle.",
    "Even your quirks are my favorite parts of the universe.",
    "The way you love makes me want to be the best version of myself.",
    "You’re my favorite part of every story I tell.",
    "You are the softest chapter in the book of my life.",
    "You are the reason I smile when no one’s watching.",
    "Your kindness is the language my heart has always spoken.",
    "Being with you is like dancing in a dream I never want to end.",
    "You laugh in colors, and I never want to see in black and white again.",
    "You are the sunrise I look forward to every morning.",
    "When you hold my hand, even gravity feels optional.",
    "You make the ordinary feel like a fairytale.",
    "You are my favorite kind of forever.",
    "Even the stars envy the way you shine.",
    "You’re the reason I look forward to tomorrow.",
    "You hug like home.",
    "You’re every love letter I’ve never written.",
    "You are my safe space in this chaotic world.",
    "You make love feel like breathing—natural, constant, and essential.",
    "Even in a crowded room, my heart looks for you.",
    "You make time slow down with just a glance.",
    "You're the melody that plays in the background of my happiest thoughts.",
    "You make the world a little softer, a little kinder."
];

