export default [
    "I love that you love animation films and watch them so often, I find it so cute",
    "I love how you get so flustered when I learn something new about you sometimes, I like getting to know you better and better",
    "I love getting to have intellectual conversations with you, I like that we can pick our brains together and learn from each other",
    "I love that you like to dress nicely and look good, I think you look so cute when you do",
    "Your Instagram aesthetic is like the most beautiful thing I’ve ever seen, I love looking at your photos and seeing the world through your eyes",
    "I love that we have Ferkie and Charles in our imaginary world",
    "I love how considerate you are and have showed that to me in so many ways",
    "Your giggle is the most adorable thing I’ve ever heard, it makes me so happy to hear you laugh",
    "Building our future together in NYC or Europe is something I look forward to every day, I'm so grateful to have found someone who shares my dreams",
    "I love your body and all its curves, I think they're so sexy and I don't know when 'fat' is even a word that comes to mind when you look at it",
    "You are my eepy little princess, and I love you so much",
    "i love the softness of your cheeks and the way you look at me",
    "You make me a better person, and everyday I try to be better for you",
    "I love that we have started to learn some Italian together",
    "Your smile is my favorite thing to see every day.",
    "I like that you hold me accountable at times, it shows how much you care about me",
    "I love that you've gotten me into R&B and Mariah Carey, and so much other new music",
    "I love all the silly reels you send me about our relationship, and how you pretend you're the boss of the relationship",
    "I love seeing your smile when I am able to Deliveroo something to you",
    "I love you're ability to be so focused and driven",
    "I love that you like to try different foods and restaurants, it makes our dates so fun and exciting",
    "You're my favorite person to come home to.",
    "I love sleeping next to you, even though you steal the blankets hehehe",
    "Our bangs are always so good, and you always look like a goddess every time",
    "I love that you try and paint my nails, even though I'm stubborn about it",
    "As embarassing as it is, doing the facetimes is always so much fun",
    "Competing to see who's less worse at tennis is one of my favorite things to do with you",
    "I love going to thrift stores and getting to say \"I think Isa would love this \" when I stroll the women's section",
    "I love being able to hold you when you have a scary dream and comfort you, it makes me feel close",
    "I love all the silly little reels I get to send you no matter how ridiculous they are, you always watch",
    "I love that you always keep me update on Sophie and send me little cute photos of her",
    "Being able to Deliveroo you food and seeing you so happy to eat is one of my favorite ways of expressing my love for you",
    "You are Bubu and I am Dudu, and I love getting to send you all those kinds of videos",
    "It's cute when you always want to pop my pimples, even thought it hurts :(",
    "I love getting to watch all the silly movies you want to watch",
    "Just coexisting with you and doing our own thing is like paradise on Earth to me",
    "I love when you pretend to know Hungarian, the extent of which you just nem",
    "Your kindness is the language my heart has always spoken.",
    "I love letting you clean my ears, it makes me feel so cared for and loved",
    "Have an amazing today baby bear, kill it!",
    "I love those lazy days where we sleep in and snuggle and then go out to study",
    "I love that we share volleyball in common and can pepper togetherrrr",
    "I love that you always know exactly which reel is going to make me laugh, it’s like you’ve memorized my sense of humor without me even realizing",
    "I love the way your face lights up when the food actually arrives, it’s one of my favorite things to be there for",
    "I love that even though the distance is hard, you’ve somehow made it feel smaller than it is, and that’s because of how much effort you put in",
    "I love that you let me learn you slowly, every little new thing I find out feels like something I get to keep",
    "I love how seriously you take your goals, watching you be driven makes me want to work harder on mine too",
    "I love that we have our own little words and references that mean nothing to anyone else but make complete sense to us",
    "I love the way you put yourself together when we go out, you have this sense of style that always makes me feel lucky to be next to you",
    "I love that you remember things I’ve told you, little details I didn’t even think you’d hold onto, it makes me feel like you really listen",
    "I love that the Italian we’re learning is kind of just ours, it’s one of those things we’re building together that has no purpose except that we like it",
    "I love hearing you talk about Sophie, the way you describe her tells me so much about how caring you are even in small, everyday things",
    "I love that when I picture what my future looks like it has you in it in a way that feels completely natural, not like a hope but like a fact",
    "I love that being with you doesn’t have to be anything special to feel good, just existing in the same space as you is enough for me",
    "I love how you get excited about things, it’s infectious and it pulls me in every time",
    "I love that you’re not afraid to be opinionated, it makes talking to you actually interesting",
    "I love how you carry yourself, there’s a confidence in you that you might not even notice you have",
    "I love that you’re someone I actually want to tell things to, not just because I should but because I want to",
    "I love how you make friends so easily, it’s something I’ve always admired about you",
    "I love that you’re not trying to be someone you’re not, there’s something really rare about that",
    "I love how you handle things when they get hard, it makes me feel like we can get through anything",
    "I love how curious you are, you’re always wanting to understand something better",
    "I love that you can make me laugh even when I’m in a bad mood, without even really trying",
    "I love that I can be boring with you and it still feels good",
    "I love how affectionate you are, you’ve never made me guess how you feel about me",
    "I love that you have your own world and your own friendships, it makes you more interesting to me not less",
    "I love that you’re not afraid to be a little silly, it makes everything more fun",
    "I love how you take care of the people around you, it’s something you do without even thinking about it",
    "I love how you commit to things, when you’re in you’re all in",
    "I love that you can hold a real conversation, you actually engage instead of just going through the motions",
    "I love that you’re someone I miss when I haven’t heard from you in just a few hours",
    "I love how I can tell what kind of mood you’re in even through a screen, I feel like I know you that well",
    "I love that being around you makes me want to be more present, not somewhere else in my head",
    "I love that you push me without making me feel pushed, it just comes from being around you"
];

